<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="com.revature.service.ClientServiceTest" tests="5" skipped="0" failures="0" errors="0" timestamp="2022-03-16T16:06:33" hostname="LAPTOP-6318QO8H" time="2.102">
  <properties/>
  <testcase name="test_getClientById_clientDoesNotExist()" classname="com.revature.service.ClientServiceTest" time="2.021"/>
  <testcase name="test_getStudentById_invalidId()" classname="com.revature.service.ClientServiceTest" time="0.005"/>
  <testcase name="testGetAllClients()" classname="com.revature.service.ClientServiceTest" time="0.051"/>
  <testcase name="testGetStudentById_positiveTest()" classname="com.revature.service.ClientServiceTest" time="0.004"/>
  <testcase name="test_getStudentById_sqlExceptionFromDao()" classname="com.revature.service.ClientServiceTest" time="0.01"/>
  <system-out><![CDATA[[Client{id=1, firstName='Bill', lastName='Doe', age=28}, Client{id=2, firstName='John', lastName='Moe', age=32}, Client{id=3, firstName='Carol', lastName='Smith', age=26}]
]]></system-out>
  <system-err><![CDATA[]]></system-err>
</testsuite>
